[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Smart Agriculture: Investigating the Applications and Impacts of Intelligent Technologies in Farming"
